apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: ru-beacon
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  TZ: {{ .Values.global.timezone | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
