{{- if .Values.webDashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: ru-beacon-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web-dashboard
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.webDashboard.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ru-beacon-web
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
