apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-postgresql
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-postgresql
  template:
    metadata:
      labels:
        app: postgres-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "rubeacon"
            - name: POSTGRES_USER
              value: "rubeacon_app"
            - name: POSTGRES_PASSWORD
              value: "change_me_prod_db_secret"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: database
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-master
